add_library(stepper_types INTERFACE)
target_include_directories(stepper_types INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)

add_library(stepper_request INTERFACE)
target_include_directories(stepper_request INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)
target_link_libraries(stepper_request INTERFACE stepper_types)

add_library(stepper_response INTERFACE)
target_include_directories(stepper_response INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)
target_link_libraries(stepper_response INTERFACE stepper_types)

add_library(stepper_service INTERFACE)
target_include_directories(stepper_service INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)
target_link_libraries(stepper_service INTERFACE service stepper_request stepper_response stepper_provider)