add_library(segway_types INTERFACE)
target_include_directories(segway_types INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)

add_library(segway_request INTERFACE)
target_include_directories(segway_request INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)
target_link_libraries(segway_request INTERFACE segway_types)

add_library(segway_response INTERFACE)
target_include_directories(segway_response INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)
target_link_libraries(segway_response INTERFACE segway_types)

add_library(segway_service INTERFACE)
target_include_directories(segway_service INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)
target_link_libraries(segway_service INTERFACE service segway_request segway_response segway_provider)