name: stm32-service-env

include:
  - ../embedded-service-framework/docker/compose.yml

services:
  stm32-dev:
    image: stm32-dev
    build:
      context: ..
      dockerfile: ./docker/dev.dockerfile
      additional_contexts:
        esf-dev-image: service:esf-dev
      network: host
    network_mode: host
    tty: true
    volumes:
      - ..:/usr/app/src