services:
  framework-dev-image-build:
    image: framework-dev-image
    build:
      context: ..
      dockerfile: ./embedded-service-framework/docker/dev.dockerfile
      network: host

  stm32-dev:
    image: stm32-dev
    build:
      context: ..
      dockerfile: ./docker/dev.dockerfile
      additional_contexts:
        framework-dev-image: service:framework-dev-image-build
      network: host
    tty: true
    volumes:
      - ..:/usr/app/src