include:
  - ../embedded-service-framework/docker/compose.yml

services:
  # STM32 development service that depends on the ESF dev image/build
  stm32-esf-dev:
    image: stm32-esf-dev-image
    build:
      context: ..
      dockerfile: ./docker/dev.dockerfile
      additional_contexts:
        esf-dev-image: service:esf-dev
    tty: true
    volumes:
      - .:/usr/app/src
