syntax = "proto3";

package segway_service;

message SegwayRequest {
	oneof request {
		SegwayEnableRequest enable_request = 1;
		SegwayStepsRequest steps_request = 2;
	}
}

message SegwayEnableRequest {
	SegwayStatus status = 1;
}

message SegwayStepsRequest {
	SegwayDirection direction = 1;
	uint32 step_duration_us = 2;
	uint32 steps_number = 3;
}

message SegwayResponse {
	SegwayResultCode result = 1;
	SegwayStatus segway_status = 2;
	string error_message = 3;
}

enum SegwayStatus {
	DISABLED = 0;
	ENABLED = 1;
}

enum SegwayDirection {
	CW = 0;
	CCW = 1;
}

enum SegwayResultCode {
	SUCCESS = 0;
	FAILURE = 1;
}