add_library(segway_provider INTERFACE)
target_include_directories(segway_provider INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)
target_link_libraries(segway_provider INTERFACE provider segway_types)

add_library(stm32_segway_provider INTERFACE)
target_include_directories(stm32_segway_provider INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)
target_link_libraries(stm32_segway_provider INTERFACE segway_provider segway_types)