name: on PR to main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "epic/*" ]

env:
  BUILD_TYPE: Debug
  CONTAINER_SRC_DIR: /usr/app/src
  CONTAINER_BIN_DIR: /usr/app/bin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    
    - name: update submodules
      working-directory: ${{github.workspace}}
      run: |
        git submodule update --init --recursive

    - name: build dev image
      working-directory: ${{github.workspace}}
      run: |
        docker compose -f docker/compose.yml build

    - name: cmake config
      working-directory: ${{github.workspace}}
      run: |
        docker run -i -v ${{github.workspace}}:${{env.CONTAINER_SRC_DIR}} -v ${{github.workspace}}/bin:${{env.CONTAINER_BIN_DIR}} stm32-dev -c "cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S ${{env.CONTAINER_SRC_DIR}} -B ${{env.CONTAINER_BIN_DIR}}"
    
    - name: build
      working-directory: ${{github.workspace}}
      run: |
        docker run -i -v ${{github.workspace}}:${{env.CONTAINER_SRC_DIR}} -v ${{github.workspace}}/bin:${{env.CONTAINER_BIN_DIR}} stm32-dev -c "cmake --build ${{env.CONTAINER_BIN_DIR}} --target stm_mcu_server"